// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: IMG_TEST

#ifndef _IMG_TEST_UI_H
#define _IMG_TEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_12_png);    // assets/12.png
LV_IMG_DECLARE(ui_img_23_png);    // assets/23.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
